// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uioiajveiqdymwubglwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpb2lhanZlaXFkeW13dWJnbHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDYzNDYsImV4cCI6MjA2NzI4MjM0Nn0.8IZs9SrJqZhJZWWc0kyPMVQZtxDvRveDl3Y5RRrtJDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});